name: Pluto Workflow

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      template_dir:
        required: false
        type: string
        default: ""
        description: "(For Kustomize deployment method) a path to a directory containing 'kustomization.yaml'"
      values_base:
        required: false
        type: string
        default: ""
        description: "(For Helm chart deployment method) Specify a path of base values.yaml (or equivalent)"
      values_overlay:
        required: false
        type: string
        default: ""
        description: "(For Helm chart deployment method) Specify a path of overlay values.yaml (or equivalent)"

jobs:
  review-k8s-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@v5.19.0
      - name: Install all-in-one Kubernetes tools in a package.
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          kubectl: '1.26.13'
      - name: Run Pluto to scan K8S Manifest generated by Kustomize and send a report to OpsLevel
        shell: bash
        env:
          UNENCRYPTED_TARGET_VERSION: ${{ secrets.TARGET_K8S_VERSION }}
          UNENCRYPTED_OPSLEVEL_PLUTO_INTEGRATION_WEBHOOK_URL: ${{ secrets.OPSLEVEL_PLUTO_INTEGRATION_WEBHOOK_URL }}
        run: |
          echo -n "> PWD..."
          pwd
          echo -n "> Files in current PWD..."
          ls -la
          
          MANIFEST_FILE=manifest.yaml

          # Generate a manifest file
          ## Kustomize
          if [[ -n "${{ inputs.template_dir }}" ]]; then
            echo -n ">>> Running Kustomize..."
            kubectl kustomize ${{ inputs.template_dir }} --output=$MANIFEST_FILE
            echo -n ">>> Kustomize run complete; manifest.yaml generated."

          ## Helm
          else
            echo -n ">>> Running helm template..."
            helm template charts/${{ inputs.service_name }} --values ${{ inputs.values_base }} --values ${{ inputs.values_overlay }} > $MANIFEST_FILE
            echo -n ">>> Helm template run complete; manifest.yaml generated."
          fi

          echo -n ">>> Output the generated file"
          cat $MANIFEST_FILE

          # Send the manifest file to Pluto
          echo -n ">>> Run Pluto scan"

          # cat $MANIFEST_FILE | pluto detect - --target-versions k8s=$UNENCRYPTED_TARGET_VERSION --ignore-deprecations --ignore-removals --output json | curl -i -s -X POST $UNENCRYPTED_OPSLEVEL_PLUTO_INTEGRATION_WEBHOOK_URL?alias=${{ inputs.service_name }} -H 'content-type: application/json' --data-binary @-

          cat $MANIFEST_FILE | pluto detect - --target-versions k8s=$UNENCRYPTED_TARGET_VERSION --ignore-deprecations --ignore-removals --output json
