name: Verify Vault Secrets Elixir

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      edges:
        required: true
        type: string
      environments:
        required: false
        type: string
        default: "staging,demo,uat,audit1,ps,production"
      vault_addr_prod:
        required: false
        type: string
        default: "https://vault.prod.thescore.is"
      vault_addr_non_prod:
        required: false
        type: string
        default: "https://vault.non-prod.thescore.is"

jobs:
  verify-vault-secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: scoremedia/devops-github-workflow
          ref: ACC-465-verify-vault-secrets-workflow
          path: shared-actions
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        shell: bash
        run: |
          cd ./shared-actions/.github/workflows/verify-vault-secrets && npm install
      - name: Get Non-Prod Token from Vault
        id: non-prod-vault-token
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          path: github-actions
          url: https://vault.non-prod.thescore.is
          role: ${{ inputs.service }}
          exportToken: true
          secrets: |
            thescore/data/infrastructure/github/tokens/scorebet-bot token | GITHUB_PAT ;

      - name: Get Prod Token from Vault
        id: prod-vault-token
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          path: github-actions
          url: https://vault.prod.thescore.is
          role: ${{ inputs.service }}
          exportToken: true
          secrets: |
            thescore/data/infrastructure/github/tokens/scorebet-bot token | GITHUB_PAT ;

      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./shared-actions/.github/workflows/verify-vault-secrets/verifyVaultSecrets.js')
            await script({github, context, core})
          service: ${{ inputs.service }}
          edges: ${{ inputs.edges }}
          non_prod_vault_token: ${{ steps.non-prod-vault-token.outputs.GITHUB_PAT }}
          prod_vault_token: ${{ steps.prod-vault-token.outputs.GITHUB_PAT }}
          environments: ${{ inputs.environments }}
          vault_addr_prod: ${{ inputs.vault_addr_prod }}
          vault_addr_non_prod: ${{ inputs.vault_addr_non_prod }}