name: Verify Vault Secrets Elixir

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      edges:
        required: true
        type: string
      environments:
        required: false
        type: string
        default: "staging,demo,uat,audit1,ps,production"

jobs:
  verify-vault-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('verify-vault-secrets/verifyVaultSecrets.js')
            await script({github, context, core})