name: Verify Vault Secrets Elixir

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      edges:
        required: true
        type: string
      environments:
        required: false
        type: string
        default: "staging,demo,uat,audit1,ps,production"

jobs:
  verify-vault-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: scoremedia/devops-github-workflow
          ref: ACC-465-verify-vault-secrets-workflow
          path: shared-actions
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          cd .github/workflows
          ls -la
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./shared-actions/.github/workflows/verify-vault-secrets/verifyVaultSecrets.js')
            await script({github, context, core})