name: Verify Vault Secrets Elixir

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      edges:
        required: true
        type: string
      path_suffixes:
        required: true
        type: string
      environments:
        required: false
        type: string
        default: "['staging','demo','uat','audit1','ps','production']"
      vault_addr_prod:
        required: false
        type: string
        default: "https://vault.prod.thescore.is"
      vault_addr_non_prod:
        required: false
        type: string
        default: "https://vault.non-prod.thescore.is"

jobs:
  retrieve-vault-secret-keys:
    runs-on: non-prod-scorebet-org-runner
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.environments) }}
        edge: ${{ fromJSON(inputs.edges) }}
        suffix: ${{ fromJSON(inputs.path_suffixes) }}
    steps:
      - name: Get Vault Keys
        id: vault-keys
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          path: github-actions
          url: ${{ matrix.env == 'production' && 'https://vault.prod.thescore.is' || 'https://vault.non-prod.thescore.is' }}
          role: identity
          exportToken: true
          secrets: |
            scorebet/subkeys/identity/${{ matrix.env }}/${{ matrix.edge }}/${{ matrix.suffix }} subkeys ;
      - name: Set Output
        id: vault-keys-output
        shell: bash
        run: |
          echo '${{ toJson(steps.vault-keys.outputs.subkeys) }}' >> ./${{ matrix.env }}-${{ matrix.edge }}-${{ matrix.suffix }}-keys.json
      - name: Upload output artifact
        id: vault-keys-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.env }}-${{ matrix.edge }}-${{ matrix.suffix }}-keys
          path: ./${{ matrix.env }}-${{ matrix.edge }}-${{ matrix.suffix }}-keys.json
      - name: Debug
        shell: bash
        run: |
          cat ./${{ matrix.env }}-${{ matrix.edge }}-${{ matrix.suffix }}-keys.json

  verify-vault-secrets:
    runs-on: non-prod-scorebet-org-runner
    needs: retrieve-vault-secret-keys
    strategy:
      matrix:
        env: ${{ fromJson(inputs.environments) }}
        edge : ${{ fromJson(inputs.edges) }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      #- uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: scoremedia/devops-github-workflow
          ref: ACC-465-verify-vault-secrets-workflow
          path: shared-actions
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        shell: bash
        run: |
          cd ./shared-actions/.github/workflows/verify-vault-secrets && npm install

      - name: Download env-edge keys artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.env }}-${{ matrix.edge }}-common-keys
          path: ${{ matrix.env }}-${{ matrix.edge }}-common-keys.json
      
      - name: Debug
        shell: bash
        run: |
          ls
          cat ${{ matrix.env }}-${{ matrix.edge }}-common-keys.json

      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./shared-actions/.github/workflows/verify-vault-secrets/verifyVaultSecrets.js')
            await script({github, context, core})
          keys: ${{fromJson(needs.retrieve-vault-secret-keys.outputs.subkeys)}}
