name: Verify Vault Secrets Elixir

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      edges:
        required: true
        type: string
      environments:
        required: false
        type: string
        default: "staging,demo,uat,audit1,ps,production"

jobs:
  verify-vault-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: scoremedia/devops-github-workflow
          ref: ACC-465-verify-vault-secrets-workflow
          path: shared-actions
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        shell: bash
        run: |
          cd ./shared-actions/.github/workflows/verify-vault-secret && snpm install
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./shared-actions/.github/workflows/verify-vault-secrets/verifyVaultSecrets.js')
            await script({github, context, core})